---

- hosts: all
  tasks:

  - name: update cache
    apt:
      update_cache: yes

  - name: Install Apache2    
    apt:
      name: apache2
      state: present


  - name: Set timezone to Africa/Lagos
    shell: timedatectl set-timezone Africa/Lagos


  - name: Display hostname
    shell: echo "<h1>Hello from $(hostname -f) , my timezone is $(timedatectl | grep 'Time zone' | awk '{print $3}')</h1>" > /var/www/html/index.html
    notify: restart_apache


  handlers:
  - name: restart_apache
    systemd:
      name: apache2
      state: restarted
      